In [5]:
import cv2
import os
import numpy as np

In [53]:
def cpd():  # 현재 디렉토리 확인
    return os.getcwd()  # 현재 파이썬프로젝트 폴더 위치 표시

In [54]:
cpd()

'C:\\Users\\PKS\\PycharmProjects\\CV2_practice'

In [55]:
def bip(video_name):  # background image processing (배경이미지 처리함수)
    input_video = video_name
    cap = cv2.VideoCapture(input_video)  # 동영상 캡처 객체 생성
    fps = cap.get(cv2.CAP_PROP_FPS)  # 초당 프레임
    fwt = round((1 / fps) * 1000)  # 프레임당 재생시간 설정 & 입력단위가 ms이므로 *1000 & 정수입력으로 round처리

    cbs = cv2.createBackgroundSubtractorKNN()  # 배경제거 객체생성함수 선언

    if cap.isOpened():  # 캡쳐객체 초기화 확인 (동영상을 불러올 수 있는지 확인하는듯)

        while cap.isOpened():  # 초기화 되는동안 영상재생
            ret, frame = cap.read()  # 프레임 추출가능(T/F), 추출한프레임

            if ret:  # run = True (캡쳐 객체 호출가능) : 동영상 재생시작
                frame = cv2.resize(frame, (720, 480)) # 프레임이미지 크기 변환 720*480
                rmbg_frame = cbs.apply(frame)  # 배경제거한 프레임 생성
                back_frame = cbs.getBackgroundImage()  # 배경 프레임 생성
                
                cv2.imshow(input_video, frame)  # 입력비디오의 프레임 이미지를 보여줌
                cv2.imshow("rmbg_" + input_video, rmbg_frame)  # 배경제거된 프레임 이미지를 보여줌
                cv2.imshow("back_" + input_video, back_frame)  # 배경 프레임 이미지를 보여줌

                if cv2.waitKey(fwt) == ord('q'):  # fps만큼 재생하다가 q입력되면 동작 종료
                    cap.release()
                    cv2.destroyAllWindows()
                    print("Stop video")
                    break

            else:  # run = False (캡쳐 객체 호출불가능) : 동영상 자동 종료
                cap.release()  # 캡쳐 자원 반납
                cv2.destroyAllWindows()  # 창종료
                print("End of playback")

    else:
        print("Can't open")

In [56]:
bip("smp.mp4")

Stop video


In [1]:
def scs(video_name):  # screenshot (영상 이미지 저장)
    input_video = video_name
    cap = cv2.VideoCapture(input_video)  # 동영상 캡처 객체 생성
    fps = cap.get(cv2.CAP_PROP_FPS)  # 초당 프레임
    fwt = round((1 / fps) * 1000)  # 프레임당 재생시간 설정 & 입력단위가 ms이므로 *1000 & 정수입력으로 round처리

    cbs = cv2.createBackgroundSubtractorKNN()  # 배경제거 객체생성함수 선언

    if cap.isOpened():  # 캡쳐객체 초기화 확인 (동영상을 불러올 수 있는지 확인하는듯)

        while cap.isOpened():  # 초기화 되는동안 영상재생
            ret, frame = cap.read()  # 프레임 추출가능(T/F), 추출한프레임

            if ret:  # run = True (캡쳐 객체 호출가능) : 동영상 재생시작
                origin_frame = cv2.resize(frame, (720, 480))  # 프레임이미지 크기 변환 720*480
                rmbg_frame = cbs.apply(origin_frame)  # 배경제거한 프레임 생성
                back_frame = cbs.getBackgroundImage()  # 배경 프레임 생성 (입력값X : 자동으로 현재 출력중인 영상을 처리함)

                cv2.imshow(input_video, origin_frame)  # 입력비디오의 프레임 이미지를 보여줌
                cv2.imshow('rmbg_' + input_video, rmbg_frame)  # 배경제거된 프레임 이미지를 보여줌
                cv2.imshow('back_' + input_video, back_frame)  # 배경 프레임 이미지를 보여줌

                if cv2.waitKey(1) == ord('s'):  # 's'입력시 함수 동작
                    frame_count = cap.get(cv2.CAP_PROP_POS_FRAMES)  # 현재 프레임 번호지정
                    cv2.imwrite('image/' + str(frame_count) + '_origin.jpg', origin_frame)  # 해당 프레임 이미지 저장
                    cv2.imwrite('image/' + str(frame_count) + '_rmbg.jpg', rmbg_frame)
                    cv2.imwrite('image/' + str(frame_count) + '_back.jpg', back_frame)
                    
                if cv2.waitKey(1) == ord('d'):  # 's'입력시 함수 동작
                    print(rmbg_frame[0, 0])
                    print(rmbg_frame[85, 207])

                if cv2.waitKey(fwt-2) == ord('q'):  # fps만큼 재생하다가 'q'입력되면 동작 종료
                    cap.release()
                    cv2.destroyAllWindows()
                    print("Stop video")
                    break

            else:  # run = False (캡쳐 객체 호출불가능) : 동영상 자동 종료
                cap.release()  # 캡쳐 자원 반납
                cv2.destroyAllWindows()  # 창종료
                print("End of playback")

    else:
        print("Can't open")

In [2]:
scs("smp.mp4")

NameError: name 'cv2' is not defined

In [6]:
def syn(origin_image, rmbg_image, back_image):  # Synthesis : 추출한 프레임 이미지 합성
    image_data = cv2.imread(origin_image)
    height, width, channel = image_data.shape
    print('width:  ', width)
    print('height: ', height)
    print('channel:', channel)
    
    a = image_data[100,200] 
    print(a)
    print(image_data)

In [7]:
syn('o.jpg', 'r.jpg', 'b.jpg')

width:   720
height:  480
channel: 3
[47 58 88]
[[[  9  36  62]
  [ 26  56  81]
  [ 33  64  87]
  ...
  [ 44  59  78]
  [ 42  57  76]
  [ 22  37  56]]

 [[ 24  53  80]
  [ 45  75 102]
  [ 52  86 110]
  ...
  [ 64  79  98]
  [ 62  77  96]
  [ 40  55  74]]

 [[ 29  63  93]
  [ 54  88 118]
  [ 62  98 128]
  ...
  [ 76  90 112]
  [ 71  85 107]
  [ 46  60  82]]

 ...

 [[ 16  27  41]
  [ 28  44  57]
  [ 29  48  63]
  ...
  [ 51  59  72]
  [ 43  51  64]
  [ 29  37  50]]

 [[ 20  29  42]
  [ 31  44  58]
  [ 30  46  62]
  ...
  [ 44  51  66]
  [ 38  46  59]
  [ 26  34  47]]

 [[ 13  22  35]
  [ 24  35  49]
  [ 20  36  52]
  ...
  [ 28  35  50]
  [ 24  32  45]
  [ 14  22  35]]]


In [17]:
origin_data = cv2.imread('o.jpg')

In [18]:
origin_data[10, 10]

array([ 39,  83, 124], dtype=uint8)

In [19]:
origin_pixel = origin_data[10, 10]

In [20]:
o_blu, o_grn, o_red = origin_pixel[0], origin_pixel[1], origin_pixel[2]
print(o_blu, o_grn, o_red)

39 83 124


In [27]:
proc_data = np.full((10, 10, 3), (0, 255, 0), dtype=np.uint8)

In [29]:
proc_data[9, 9]

array([  0, 255,   0], dtype=uint8)

In [40]:
def shc(input_image):
    input_data = np.full((100, 200, 3), (0, 255, 0), dtype=np.uint8)
    input_frame = cv2.imread(input_image)
    while True:
        cv2.imshow('input_image', input_frame)
        cv2.imshow('input_data', input_data)
        if cv2.waitKey(1) == ord('q'):
            break
    cv2.destroyAllWindows()  # 창종료
    return cv2.imread(input_frame)

In [41]:
shc('o.jpg')

TypeError: Can't convert object of type 'numpy.ndarray' to 'str' for 'filename'